version: "3.1"

services:
  db:
    image: mysql
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.db
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - app_network
  www:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    networks:
      - app_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test

networks:
  app_network:
    name: app_network
    driver: bridge

volumes:
  persistent:
       